services:
  go-nitro-alice:
    image: bpi/go-nitro:stack
    hostname: go-nitro-alice
    restart: on-failure
    env_file:
      - ../config/go-nitro/alice.env
    volumes:
      - go-nitro-data-alice:/app/data
    ports:
      - "3006"
      - "4006"
      - "5006"
      - "4106"
      - "4206"
      - "4216"

  go-nitro-bob:
    image: bpi/go-nitro:stack
    hostname: go-nitro-bob
    restart: on-failure
    env_file:
      - ../config/go-nitro/bob.env
    volumes:
      - go-nitro-data-bob:/app/data
    ports:
      - "3007"
      - "4007"
      - "5007"
      - "4107"
      - "4207"
      - "4217"

  go-nitro-bootnode:
    image: bpi/go-nitro:stack
    hostname: go-nitro-bootnode
    restart: on-failure
    env_file:
      - ../config/go-nitro/bootnode.env
    volumes:
      - go-nitro-data-bootnode:/app/data
    ports:
      - "9090"
      - "3008"
      - "4008"
      - "4108"
      - "4208"
      - "5008"

volumes:
  go-nitro-data-alice:
  go-nitro-data-bob:
  go-nitro-data-bootnode: