name: go-nitro
description: "go-nitro"
containers:
  - name: bpi/go-nitro
    ref: bozemanpass/go-nitro-stack
    path: container-build/bpi-go-nitro
pods:
  - name: go-nitro
    repository: bozemanpass/go-nitro-stack
    path: go-nitro
    post_start_command: "deploy-create2.sh"
